### ISSUE TITLE
Add Python 3 support

### ISSUE THREAD

**Issue by ronnix** [pydron/ifaddr#10]
Hi there!

When trying to use ifaddr with Python 3.6.1, I get this error:
```
$ python
Python 3.6.1 (default, Mar 27 2017, 12:33:38)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import ifaddr
>>> ifaddr.get_adapters()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ronan/.virtualenvs/ifaddr/lib/python3.6/site-packages/ifaddr/_posix.py", line 67, in get_adapters
    prefixlen = ipaddress.IPv4Network(unicode('0.0.0.0/' + netmask)).prefixlen
NameError: name 'unicode' is not defined
```

I've seen that @calebmadrigal's fork includes some changes to work with Python 3. Maybe they can be included?

**Comment by pydron** [comment]
Unfortunately, the changes of @calebmadrigal break support with Python 2. It should be fairly easy to make it support both though. Just have to find some time to do it.

**Comment by ronnix** [comment]
Thanks for the reply. Hopefully you can find some time for it, or someone can provide a pull request!

**Comment by ronnix** [comment]
Looks like 0.1.4 works on both Python 2 and Python 3, so I'm closing this issue.
