### ISSUE TITLE
Release tag for version 0.1.4 missing

### ISSUE THREAD

**Issue by pluehne** [pydron/ifaddr#11]
Dear maintainers, [PyPi shows that there’s a 0.1.4 release](https://pypi.org/project/ifaddr/#history), but it [doesn’t appear to have a corresponding tag here on GitHub](https://github.com/pydron/ifaddr/releases). It would be nice if you could publish the release tag here as well :slightly_smiling_face:. That would be helpful to package maintainers outside of PyPi. Thanks!

**Comment by pydron** [comment]
Yes, I missed that. Thanks for letting me know.

Added 0.1.4 and also 0.1.5 after merging your fix.

**Comment by pluehne** [comment]
Thanks for pushing the missing 0.1.4 tag as well as the new 0.1.5 release with the fix from #12 so quickly :+1:!
