### ISSUE TITLE
Type annotations are missing

### ISSUE THREAD

**Issue by thtrummer** [pydron/ifaddr#34]
Ideally this would use the PEP484 style though this would require dropping Python 2.7 support (I believe). Alternatively stub files (.pyi) could be created. I'm happy to provide a patch if you're interested.

**Comment by jstasiak** [comment]
Hey @thtrummer, it seems that this package is not being installed on Python 2 too often (checked https://pypistats.org/packages/ifaddr) so I dropped 2.7 and 3.5 support and the way forward on this is more obvious now. A patch adding type hints would be very much appreciated!
