### ISSUE TITLE
Default gateway

### ISSUE THREAD

**Issue by farmio** [pydron/ifaddr#41]
Hi 👋!

Would it be possible to add a way to get the default gateway like it is on `netifaces`?
```py
>>> gws = netifaces.gateways()
>>> gws['default'][netifaces.AF_INET]
('10.0.1.1', 'en0')
```

**Comment by jstasiak** [comment]
Hey, I don't have resources or knowledge to implement this (especially in a cross-platform way) but I'll happily accept a PR that does it. I'll close this issue as there's nothing to add here, really – pull requests are very welcome.
