### ISSUE TITLE
(feature request) Make returned objects pretty-printable

### ISSUE THREAD

**Issue by pyhedgehog** [pydron/ifaddr#5]
I have a solution:
1. Derive classes from [collections.namedtuple](https://docs.python.org/2/library/collections.html#collections.namedtuple)
2. Wait for accepting [pprint for namedtuple](https://gist.github.com/pyhedgehog/5f85fc335a0a36aa308c) patch

**Comment by smurn** [comment]
Hi Pyhedgehog,
I'm not quite sure what you are suggesting to solve. What exactly do you mean by "pretty-printable"? And in what regard are the existing `__repr__` implementations insufficient?

best,
Stefan

**Comment by pyhedgehog** [comment]
By pretty-printable I mean ability to use `pprint` stdlib module. Check #6 for my proposal.

**Comment by jstasiak** [comment]
It would required patched Python so sadly I believe this won't happen (please reopen if it's possible and I'm wrong).
